### PR TITLE
compatible with symfony 4

### PR DESCRIPTION
**Pull request by Pchol**

### CODE REVIEW

**Comment by gremo** [comment]
Have you tested it with Symfony 4? Will it work?

**Comment by Pchol** [comment]
> Have you tested it with Symfony 4? Will it work?

find bug, add second commit with fix
should work

**Comment by gremo** [comment]
Are you sure, can I merge? Please also squash the commits into just one 👍

**Comment by Pchol** [comment]
Done, can merge

**Comment by gremo** [comment]
Thanks @Pchol

**Pull request merged**
